name: Publish MkDocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Mkdocs to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: |
          poetry env use "3.11"
          poetry install --only docs

      - name: Copy notebooks into docs
        run: cp -r notebooks/* docs/ | echo "No notebooks found"

      - name: Deploy Mkdocs
        run: poetry run mkdocs gh-deploy --force
